/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	scheme "github.com/kubeovn/kube-ovn/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VpcBmsConnectionsGetter has a method to return a VpcBmsConnectionInterface.
// A group's client should implement this interface.
type VpcBmsConnectionsGetter interface {
	VpcBmsConnections() VpcBmsConnectionInterface
}

// VpcBmsConnectionInterface has methods to work with VpcBmsConnection resources.
type VpcBmsConnectionInterface interface {
	Create(ctx context.Context, vpcBmsConnection *v1.VpcBmsConnection, opts metav1.CreateOptions) (*v1.VpcBmsConnection, error)
	Update(ctx context.Context, vpcBmsConnection *v1.VpcBmsConnection, opts metav1.UpdateOptions) (*v1.VpcBmsConnection, error)
	UpdateStatus(ctx context.Context, vpcBmsConnection *v1.VpcBmsConnection, opts metav1.UpdateOptions) (*v1.VpcBmsConnection, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.VpcBmsConnection, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.VpcBmsConnectionList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VpcBmsConnection, err error)
	VpcBmsConnectionExpansion
}

// vpcBmsConnections implements VpcBmsConnectionInterface
type vpcBmsConnections struct {
	client rest.Interface
}

// newVpcBmsConnections returns a VpcBmsConnections
func newVpcBmsConnections(c *KubeovnV1Client) *vpcBmsConnections {
	return &vpcBmsConnections{
		client: c.RESTClient(),
	}
}

// Get takes name of the vpcBmsConnection, and returns the corresponding vpcBmsConnection object, and an error if there is any.
func (c *vpcBmsConnections) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.VpcBmsConnection, err error) {
	result = &v1.VpcBmsConnection{}
	err = c.client.Get().
		Resource("vpcbmsconnections").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VpcBmsConnections that match those selectors.
func (c *vpcBmsConnections) List(ctx context.Context, opts metav1.ListOptions) (result *v1.VpcBmsConnectionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.VpcBmsConnectionList{}
	err = c.client.Get().
		Resource("vpcbmsconnections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vpcBmsConnections.
func (c *vpcBmsConnections) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("vpcbmsconnections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vpcBmsConnection and creates it.  Returns the server's representation of the vpcBmsConnection, and an error, if there is any.
func (c *vpcBmsConnections) Create(ctx context.Context, vpcBmsConnection *v1.VpcBmsConnection, opts metav1.CreateOptions) (result *v1.VpcBmsConnection, err error) {
	result = &v1.VpcBmsConnection{}
	err = c.client.Post().
		Resource("vpcbmsconnections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vpcBmsConnection).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vpcBmsConnection and updates it. Returns the server's representation of the vpcBmsConnection, and an error, if there is any.
func (c *vpcBmsConnections) Update(ctx context.Context, vpcBmsConnection *v1.VpcBmsConnection, opts metav1.UpdateOptions) (result *v1.VpcBmsConnection, err error) {
	result = &v1.VpcBmsConnection{}
	err = c.client.Put().
		Resource("vpcbmsconnections").
		Name(vpcBmsConnection.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vpcBmsConnection).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vpcBmsConnections) UpdateStatus(ctx context.Context, vpcBmsConnection *v1.VpcBmsConnection, opts metav1.UpdateOptions) (result *v1.VpcBmsConnection, err error) {
	result = &v1.VpcBmsConnection{}
	err = c.client.Put().
		Resource("vpcbmsconnections").
		Name(vpcBmsConnection.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vpcBmsConnection).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vpcBmsConnection and deletes it. Returns an error if one occurs.
func (c *vpcBmsConnections) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("vpcbmsconnections").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vpcBmsConnections) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("vpcbmsconnections").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vpcBmsConnection.
func (c *vpcBmsConnections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VpcBmsConnection, err error) {
	result = &v1.VpcBmsConnection{}
	err = c.client.Patch(pt).
		Resource("vpcbmsconnections").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
