/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVpcNatGatewayIpips implements VpcNatGatewayIpipInterface
type FakeVpcNatGatewayIpips struct {
	Fake *FakeKubeovnV1
}

var vpcnatgatewayipipsResource = v1.SchemeGroupVersion.WithResource("vpcnatgatewayipips")

var vpcnatgatewayipipsKind = v1.SchemeGroupVersion.WithKind("VpcNatGatewayIpip")

// Get takes name of the vpcNatGatewayIpip, and returns the corresponding vpcNatGatewayIpip object, and an error if there is any.
func (c *FakeVpcNatGatewayIpips) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.VpcNatGatewayIpip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(vpcnatgatewayipipsResource, name), &v1.VpcNatGatewayIpip{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.VpcNatGatewayIpip), err
}

// List takes label and field selectors, and returns the list of VpcNatGatewayIpips that match those selectors.
func (c *FakeVpcNatGatewayIpips) List(ctx context.Context, opts metav1.ListOptions) (result *v1.VpcNatGatewayIpipList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(vpcnatgatewayipipsResource, vpcnatgatewayipipsKind, opts), &v1.VpcNatGatewayIpipList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.VpcNatGatewayIpipList{ListMeta: obj.(*v1.VpcNatGatewayIpipList).ListMeta}
	for _, item := range obj.(*v1.VpcNatGatewayIpipList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vpcNatGatewayIpips.
func (c *FakeVpcNatGatewayIpips) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(vpcnatgatewayipipsResource, opts))
}

// Create takes the representation of a vpcNatGatewayIpip and creates it.  Returns the server's representation of the vpcNatGatewayIpip, and an error, if there is any.
func (c *FakeVpcNatGatewayIpips) Create(ctx context.Context, vpcNatGatewayIpip *v1.VpcNatGatewayIpip, opts metav1.CreateOptions) (result *v1.VpcNatGatewayIpip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(vpcnatgatewayipipsResource, vpcNatGatewayIpip), &v1.VpcNatGatewayIpip{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.VpcNatGatewayIpip), err
}

// Update takes the representation of a vpcNatGatewayIpip and updates it. Returns the server's representation of the vpcNatGatewayIpip, and an error, if there is any.
func (c *FakeVpcNatGatewayIpips) Update(ctx context.Context, vpcNatGatewayIpip *v1.VpcNatGatewayIpip, opts metav1.UpdateOptions) (result *v1.VpcNatGatewayIpip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(vpcnatgatewayipipsResource, vpcNatGatewayIpip), &v1.VpcNatGatewayIpip{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.VpcNatGatewayIpip), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVpcNatGatewayIpips) UpdateStatus(ctx context.Context, vpcNatGatewayIpip *v1.VpcNatGatewayIpip, opts metav1.UpdateOptions) (*v1.VpcNatGatewayIpip, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(vpcnatgatewayipipsResource, "status", vpcNatGatewayIpip), &v1.VpcNatGatewayIpip{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.VpcNatGatewayIpip), err
}

// Delete takes name of the vpcNatGatewayIpip and deletes it. Returns an error if one occurs.
func (c *FakeVpcNatGatewayIpips) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(vpcnatgatewayipipsResource, name, opts), &v1.VpcNatGatewayIpip{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVpcNatGatewayIpips) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(vpcnatgatewayipipsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.VpcNatGatewayIpipList{})
	return err
}

// Patch applies the patch and returns the patched vpcNatGatewayIpip.
func (c *FakeVpcNatGatewayIpips) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VpcNatGatewayIpip, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(vpcnatgatewayipipsResource, name, pt, data, subresources...), &v1.VpcNatGatewayIpip{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.VpcNatGatewayIpip), err
}
