/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/kubeovn/kube-ovn/pkg/apis/kubeovn/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VpcBmsConnectionLister helps list VpcBmsConnections.
// All objects returned here must be treated as read-only.
type VpcBmsConnectionLister interface {
	// List lists all VpcBmsConnections in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.VpcBmsConnection, err error)
	// Get retrieves the VpcBmsConnection from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.VpcBmsConnection, error)
	VpcBmsConnectionListerExpansion
}

// vpcBmsConnectionLister implements the VpcBmsConnectionLister interface.
type vpcBmsConnectionLister struct {
	indexer cache.Indexer
}

// NewVpcBmsConnectionLister returns a new VpcBmsConnectionLister.
func NewVpcBmsConnectionLister(indexer cache.Indexer) VpcBmsConnectionLister {
	return &vpcBmsConnectionLister{indexer: indexer}
}

// List lists all VpcBmsConnections in the indexer.
func (s *vpcBmsConnectionLister) List(selector labels.Selector) (ret []*v1.VpcBmsConnection, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.VpcBmsConnection))
	})
	return ret, err
}

// Get retrieves the VpcBmsConnection from the index for a given name.
func (s *vpcBmsConnectionLister) Get(name string) (*v1.VpcBmsConnection, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("vpcbmsconnection"), name)
	}
	return obj.(*v1.VpcBmsConnection), nil
}
